- name: Install Docker and cracked Jira
  hosts: localhost
  become: yes
  vars:
    vault_addr: "http://77.221.140.212:8201"
    vault_secret_path: "secret/jira"
  vars_files:
    - secret_vault.yml
  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
    
    - name: Getting HashiCorp secrets
      community.hashi_vault.hashi_vault:
         url: "{{ vault_addr }}"
         secret: "{{ vault_secret_path }}"
         token: "{{ vault_token }}"
      register: vault_secrets
    
    - name: Templating env file
      ansible.builtin.template:
        src: variables.env.j2
        dest: variables.env
        mode: '0644'
    
    - name: Run Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d